-- transcript-search schema, Postgres edition.
-- Generated from schema.sql with `npx libsql-pg convert-schema`, then reviewed by hand:
-- the FTS5 virtual table became a real table with a generated tsvector column.
-- Applied by migrate() in src/db/index.ts when DATABASE_URL is postgres://; keep the
-- two files in step. Types: INTEGER -> bigint, REAL -> double precision, TEXT stays text.

create table if not exists companies (
  id text PRIMARY KEY,
  name text NOT NULL,
  cik text,
  sector text,
  industry text,
  created_at text NOT NULL
);

create table if not exists securities (
  id text PRIMARY KEY,
  company_id text REFERENCES companies(id),
  exchange text,
  asset_class text,
  tradable bigint DEFAULT 1,
  status text
);

create table if not exists tickers (
  symbol text PRIMARY KEY,
  security_id text REFERENCES securities(id),
  company_id text REFERENCES companies(id),
  active bigint DEFAULT 1
);

create table if not exists symbols (
  symbol text PRIMARY KEY,
  name text NOT NULL,
  exchange text,
  asset_class text,
  status text,
  tradable bigint NOT NULL DEFAULT 1,
  source text NOT NULL,
  updated_at text NOT NULL,
  name_search text NOT NULL
);

create table if not exists executives (
  id text PRIMARY KEY,
  company_id text REFERENCES companies(id),
  name text NOT NULL,
  title text
);

create table if not exists events (
  id text PRIMARY KEY,
  company_id text REFERENCES companies(id),
  event_type text NOT NULL,
  title text,
  event_date text,
  created_at text NOT NULL
);

create table if not exists documents (
  id text PRIMARY KEY,
  event_id text REFERENCES events(id),
  provider_id text NOT NULL,
  title text,
  url text NOT NULL,
  event_type text NOT NULL,
  published_at text,
  content_type text,
  local_path text,
  checksum text,
  fetched_at text,
  meta_json text,
  created_at text NOT NULL,
  publisher text,
  source_tier bigint,
  paywalled bigint DEFAULT 0,
  media_url text,
  media_type text,
  duration_ms bigint,
  provenance text,
  asr_model text,
  asr_version text
);

create table if not exists transcripts (
  id text PRIMARY KEY,
  document_id text REFERENCES documents(id),
  primary_ticker text,
  event_date text,
  language text DEFAULT 'en',
  created_at text NOT NULL
);

create table if not exists transcript_segments (
  id text PRIMARY KEY,
  transcript_id text REFERENCES transcripts(id),
  seg_index bigint NOT NULL,
  speaker text,
  speaker_title text,
  text text NOT NULL,
  start_ms bigint,
  end_ms bigint
);

-- Full-text search over transcript segments. SQLite uses an FTS5 virtual table
-- (schema.sql); here it is a plain table with a generated tsvector column and a
-- GIN index. Inserts are identical; the match predicate lives in src/db/fts.ts.
create table if not exists segments_fts (
  id            bigint generated by default as identity primary key,
  text          text NOT NULL,
  speaker       text,
  ticker        text,
  segment_id    text,
  transcript_id text,
  event_date    text,
  search        tsvector generated always as (
                  to_tsvector('english', coalesce(text, '') || ' ' || coalesce(speaker, '') || ' ' || coalesce(ticker, ''))
                ) stored
);

CREATE INDEX IF NOT EXISTS idx_segments_fts_search ON segments_fts USING gin (search);

CREATE INDEX IF NOT EXISTS idx_segments_fts_segment ON segments_fts(segment_id);

create table if not exists speakers (
  id text PRIMARY KEY,
  name text NOT NULL,
  title text,
  company_id text REFERENCES companies(id)
);

create table if not exists boilerplate_shingles (
  shingle text PRIMARY KEY,
  issuer_count bigint NOT NULL,
  updated_at text NOT NULL
);

create table if not exists corroborations (
  id text PRIMARY KEY,
  ticker text NOT NULL,
  claim_signal_id text,
  claim_source_url text,
  corroborating_doc_id text,
  corroborating_url text,
  publisher text,
  source_tier bigint NOT NULL,
  lag_days bigint,
  relation text NOT NULL,
  overlap double precision,
  confidence double precision,
  created_at text NOT NULL
);

create table if not exists quotes (
  id text PRIMARY KEY,
  segment_id text REFERENCES transcript_segments(id),
  ticker text,
  speaker text,
  quote text NOT NULL,
  source_url text,
  evidence_hash text
);

create table if not exists signals (
  id text PRIMARY KEY,
  ticker text NOT NULL,
  speaker text,
  speaker_title text,
  event_date text,
  event_type text,
  signal_type text,
  direction text,
  strength double precision,
  novelty double precision,
  specificity double precision,
  quote text,
  context_before text,
  context_after text,
  source_url text,
  evidence_hash text,
  created_at text NOT NULL,
  source_tier bigint,
  is_boilerplate bigint DEFAULT 0,
  boilerplate_reasons text,
  speaker_confidence double precision,
  start_ms bigint,
  provenance text
);

create table if not exists contradictions (
  id text PRIMARY KEY,
  ticker text NOT NULL,
  description text,
  claim_evidence_id text,
  counter_evidence_id text,
  severity double precision
);

create table if not exists relationships (
  id text PRIMARY KEY,
  from_ticker text NOT NULL,
  to_ticker text NOT NULL,
  kind text NOT NULL,
  confidence double precision
);

create table if not exists market_snapshots (
  id text PRIMARY KEY,
  ticker text NOT NULL,
  feed text,
  delayed bigint,
  last_price double precision,
  bid double precision,
  ask double precision,
  prev_close double precision,
  snapshot_json text,
  request_id text,
  fetched_at text NOT NULL
);

create table if not exists market_bars (
  id text PRIMARY KEY,
  ticker text NOT NULL,
  timeframe text NOT NULL,
  ts text NOT NULL,
  open double precision,
  high double precision,
  low double precision,
  close double precision,
  volume double precision,
  vwap double precision,
  adjustment text,
  feed text,
  UNIQUE(ticker, timeframe, ts, adjustment)
);

create table if not exists fundamentals (
  id text PRIMARY KEY,
  ticker text NOT NULL,
  as_of text NOT NULL,
  facts_json text NOT NULL,
  source text
);

create table if not exists guidance (
  id text PRIMARY KEY,
  ticker text NOT NULL,
  period text,
  metric text,
  value_json text,
  source_url text,
  created_at text NOT NULL
);

create table if not exists corporate_actions (
  id text PRIMARY KEY,
  ticker text NOT NULL,
  kind text,
  ex_date text,
  detail_json text
);

create table if not exists risk_flags (
  id text PRIMARY KEY,
  ticker text NOT NULL,
  flag text NOT NULL,
  detail text,
  observed_at text
);

create table if not exists analyses (
  id text PRIMARY KEY,
  strategy_version text NOT NULL,
  ticker text NOT NULL,
  topic text NOT NULL,
  as_of text NOT NULL,
  horizon_quarters bigint NOT NULL,
  provider text NOT NULL,
  model text NOT NULL,
  prompt_hash text NOT NULL,
  input_hash text NOT NULL,
  output_json text NOT NULL,
  overall_score double precision NOT NULL,
  confidence double precision NOT NULL,
  created_at text NOT NULL
);

create table if not exists analysis_evidence (
  id text PRIMARY KEY,
  analysis_id text REFERENCES analyses(id),
  evidence_id text NOT NULL,
  kind text,
  ticker text,
  source_url text,
  text text,
  hash text,
  observed_at text
);

create table if not exists model_runs (
  id text PRIMARY KEY,
  analysis_id text REFERENCES analyses(id),
  provider text NOT NULL,
  model text NOT NULL,
  input_tokens bigint,
  output_tokens bigint,
  cost_usd double precision,
  created_at text NOT NULL
);

create table if not exists reports (
  ticker text PRIMARY KEY,
  payload_json text NOT NULL,
  company_name text,
  last_price double precision,
  overall_score double precision,
  confidence double precision,
  classification text,
  ai_provider text,
  ai_model text,
  ai_generated_at text,
  source_count bigint NOT NULL DEFAULT 0,
  signal_count bigint NOT NULL DEFAULT 0,
  generated_at text NOT NULL,
  first_generated_at text NOT NULL,
  generated_by text
);

create table if not exists rankings (
  id text PRIMARY KEY,
  strategy_version text NOT NULL,
  topic text NOT NULL,
  as_of text NOT NULL,
  horizon_quarters bigint NOT NULL,
  ranking_json text NOT NULL,
  created_at text NOT NULL
);

create table if not exists strategies (
  version text PRIMARY KEY,
  weights_json text NOT NULL,
  prompt_hash text,
  notes text,
  created_at text NOT NULL
);

create table if not exists backtests (
  id text PRIMARY KEY,
  strategy_version text NOT NULL,
  topic text,
  as_of text,
  horizon_quarters bigint,
  metrics_json text,
  created_at text NOT NULL
);

create table if not exists backtest_positions (
  id text PRIMARY KEY,
  backtest_id text REFERENCES backtests(id),
  ticker text NOT NULL,
  entry_date text,
  entry_price double precision,
  exit_date text,
  exit_price double precision,
  return_pct double precision,
  score double precision,
  confidence double precision
);

create table if not exists providers (
  id text PRIMARY KEY,
  kind text NOT NULL,
  enabled bigint DEFAULT 1,
  config_json text
);

create table if not exists downloads (
  id text PRIMARY KEY,
  document_id text REFERENCES documents(id),
  url text NOT NULL,
  status text,
  checksum text,
  bytes bigint,
  fetched_at text
);

create table if not exists jobs (
  id text PRIMARY KEY,
  kind text NOT NULL,
  status text NOT NULL,
  payload_json text,
  error text,
  created_at text NOT NULL,
  updated_at text
);

create table if not exists users (
  id text PRIMARY KEY,
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  email_verified_at text,
  display_name text,
  created_at text NOT NULL,
  updated_at text,
  last_login_at text,
  disabled bigint NOT NULL DEFAULT 0,
  digest_frequency text NOT NULL DEFAULT 'daily',
  digest_last_sent_at text,
  digest_unsub_token text
);

create table if not exists sessions (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id),
  token_hash text NOT NULL UNIQUE,
  created_at text NOT NULL,
  expires_at text NOT NULL,
  revoked_at text,
  user_agent text,
  ip text
);

create table if not exists auth_tokens (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id),
  kind text NOT NULL,
  token_hash text NOT NULL UNIQUE,
  created_at text NOT NULL,
  expires_at text NOT NULL,
  consumed_at text
);

create table if not exists watchlist_items (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id),
  ticker text NOT NULL,
  note text,
  created_at text NOT NULL,
  UNIQUE(user_id, ticker)
);

create table if not exists credits_ledger (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id),
  delta bigint NOT NULL,
  reason text NOT NULL,
  idem text,
  note text,
  created_at text NOT NULL,
  UNIQUE(user_id, reason, idem)
);

create table if not exists credit_purchases (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id),
  payment_id text NOT NULL UNIQUE,
  package_id text NOT NULL,
  credits bigint NOT NULL,
  amount_usd double precision NOT NULL,
  blockchain text,
  status text NOT NULL,
  payment_url text,
  created_at text NOT NULL,
  updated_at text
);

create table if not exists digest_sends (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id),
  frequency text NOT NULL,
  period_key text NOT NULL,
  covering text NOT NULL,
  tickers bigint NOT NULL,
  status text NOT NULL,
  transport text,
  error text,
  sent_at text,
  created_at text NOT NULL,
  UNIQUE(user_id, period_key)
);

create table if not exists auth_attempts (
  id text PRIMARY KEY,
  bucket text NOT NULL,
  created_at text NOT NULL
);

create table if not exists nichedb_cursor (
  "key" text PRIMARY KEY,
  value text NOT NULL,
  updated_at text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_signals_ticker ON signals(ticker);

CREATE INDEX IF NOT EXISTS idx_corrob_ticker ON corroborations(ticker, relation);

CREATE INDEX IF NOT EXISTS idx_documents_publisher ON documents(publisher);

CREATE INDEX IF NOT EXISTS idx_riskflags_ticker ON risk_flags(ticker, flag);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id, expires_at);

CREATE INDEX IF NOT EXISTS idx_authtokens_user ON auth_tokens(user_id, kind);

CREATE INDEX IF NOT EXISTS idx_authattempts_bucket ON auth_attempts(bucket, created_at);

CREATE INDEX IF NOT EXISTS idx_watchlist_user ON watchlist_items(user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_credits_user ON credits_ledger(user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_digest_sends_period ON digest_sends(period_key, user_id);

CREATE INDEX IF NOT EXISTS idx_reports_generated ON reports(generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_symbols_name ON symbols(name_search);

CREATE INDEX IF NOT EXISTS idx_symbols_updated ON symbols(updated_at);

CREATE INDEX IF NOT EXISTS idx_reports_score ON reports(overall_score DESC);

CREATE INDEX IF NOT EXISTS idx_users_digest ON users(digest_frequency);

CREATE INDEX IF NOT EXISTS idx_purchases_user ON credit_purchases(user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_bars_ticker_tf ON market_bars(ticker, timeframe, ts);

CREATE INDEX IF NOT EXISTS idx_analyses_ticker ON analyses(ticker, as_of);

CREATE INDEX IF NOT EXISTS idx_segments_transcript ON transcript_segments(transcript_id, seg_index);
